#!/usr/bin/env python3
import json
import os

# Base product template data - 120 products across all categories
products = [
    {"name": "Whole Milk", "category": "dairy", "base_price": 3.48},
    {"name": "2% Milk", "category": "dairy", "base_price": 3.28},
    {"name": "Skim Milk", "category": "dairy", "base_price": 3.18},
    {"name": "Eggs Large Grade A", "category": "dairy", "base_price": 2.47},
    {"name": "Cheddar Cheese", "category": "dairy", "base_price": 2.38},
    {"name": "Mozzarella Cheese", "category": "dairy", "base_price": 2.67},
    {"name": "Swiss Cheese", "category": "dairy", "base_price": 3.18},
    {"name": "Yogurt Vanilla", "category": "dairy", "base_price": 2.98},
    {"name": "Yogurt Greek", "category": "dairy", "base_price": 3.27},
    {"name": "Sour Cream", "category": "dairy", "base_price": 1.98},
    {"name": "Butter Salted", "category": "dairy", "base_price": 3.47},
    {"name": "Whipped Cream", "category": "dairy", "base_price": 1.98},
    {"name": "Bananas", "category": "produce", "base_price": 0.58},
    {"name": "Apples Gala", "category": "produce", "base_price": 2.99},
    {"name": "Apples Granny Smith", "category": "produce", "base_price": 3.49},
    {"name": "Oranges Valencia", "category": "produce", "base_price": 3.99},
    {"name": "Lemons", "category": "produce", "base_price": 1.99},
    {"name": "Limes", "category": "produce", "base_price": 1.49},
    {"name": "Strawberries Fresh", "category": "produce", "base_price": 3.47},
    {"name": "Blueberries", "category": "produce", "base_price": 4.99},
    {"name": "Raspberries", "category": "produce", "base_price": 4.49},
    {"name": "Grapes Red", "category": "produce", "base_price": 3.99},
    {"name": "Watermelon", "category": "produce", "base_price": 6.99},
    {"name": "Cantaloupes", "category": "produce", "base_price": 4.99},
    {"name": "Pineapple", "category": "produce", "base_price": 4.99},
    {"name": "Mangoes", "category": "produce", "base_price": 3.99},
    {"name": "Tomatoes Beefsteak", "category": "produce", "base_price": 2.49},
    {"name": "Tomatoes Cherry", "category": "produce", "base_price": 2.99},
    {"name": "Bell Peppers Red", "category": "produce", "base_price": 3.49},
    {"name": "Bell Peppers Yellow", "category": "produce", "base_price": 3.49},
    {"name": "Bell Peppers Green", "category": "produce", "base_price": 2.49},
    {"name": "Cucumbers", "category": "produce", "base_price": 1.27},
    {"name": "Lettuce Iceberg", "category": "produce", "base_price": 1.47},
    {"name": "Lettuce Romaine", "category": "produce", "base_price": 2.47},
    {"name": "Spinach Fresh", "category": "produce", "base_price": 1.97},
    {"name": "Kale", "category": "produce", "base_price": 2.99},
    {"name": "Broccoli Crowns", "category": "produce", "base_price": 1.97},
    {"name": "Cauliflower", "category": "produce", "base_price": 2.47},
    {"name": "Carrots Baby", "category": "produce", "base_price": 0.79},
    {"name": "Carrots Regular", "category": "produce", "base_price": 0.99},
    {"name": "Potatoes Russet", "category": "produce", "base_price": 3.99},
    {"name": "Potatoes Red", "category": "produce", "base_price": 4.99},
    {"name": "Sweet Potatoes", "category": "produce", "base_price": 5.99},
    {"name": "Onions Yellow", "category": "produce", "base_price": 1.49},
    {"name": "Onions Red", "category": "produce", "base_price": 1.99},
    {"name": "Garlic", "category": "produce", "base_price": 1.29},
    {"name": "Zucchini", "category": "produce", "base_price": 1.99},
    {"name": "Chicken Breast Boneless", "category": "meat", "base_price": 3.24},
    {"name": "Chicken Thighs", "category": "meat", "base_price": 2.99},
    {"name": "Ground Chicken", "category": "meat", "base_price": 3.49},
    {"name": "Ground Beef 80/20", "category": "meat", "base_price": 4.94},
    {"name": "Ground Beef 90/10", "category": "meat", "base_price": 5.99},
    {"name": "Beef Steak Ribeye", "category": "meat", "base_price": 7.47},
    {"name": "Beef Roast", "category": "meat", "base_price": 5.99},
    {"name": "Pork Chops", "category": "meat", "base_price": 3.44},
    {"name": "Pork Ground", "category": "meat", "base_price": 3.99},
    {"name": "Turkey Ground", "category": "meat", "base_price": 3.97},
    {"name": "Turkey Breast", "category": "meat", "base_price": 5.99},
    {"name": "Salmon Fillet", "category": "meat", "base_price": 7.47},
    {"name": "Cod Fillet", "category": "meat", "base_price": 6.99},
    {"name": "Shrimp Frozen", "category": "meat", "base_price": 8.97},
    {"name": "Bacon", "category": "meat", "base_price": 4.97},
    {"name": "Sausage Links", "category": "meat", "base_price": 4.27},
    {"name": "Whole Wheat Bread", "category": "bakery", "base_price": 1.48},
    {"name": "White Bread", "category": "bakery", "base_price": 1.27},
    {"name": "Rye Bread", "category": "bakery", "base_price": 1.97},
    {"name": "Bread Rolls", "category": "bakery", "base_price": 2.47},
    {"name": "English Muffins", "category": "bakery", "base_price": 2.27},
    {"name": "Bagels", "category": "bakery", "base_price": 3.47},
    {"name": "Tortillas Flour", "category": "bakery", "base_price": 1.27},
    {"name": "Tortillas Corn", "category": "bakery", "base_price": 1.47},
    {"name": "Pita Bread", "category": "bakery", "base_price": 1.97},
    {"name": "Cereal Whole Grain", "category": "pantry", "base_price": 2.87},
    {"name": "Cereal Corn Flakes", "category": "pantry", "base_price": 1.98},
    {"name": "Oatmeal", "category": "pantry", "base_price": 2.47},
    {"name": "Pasta Spaghetti", "category": "pantry", "base_price": 0.88},
    {"name": "Pasta Penne", "category": "pantry", "base_price": 0.88},
    {"name": "Rice White Long Grain", "category": "pantry", "base_price": 4.97},
    {"name": "Rice Brown", "category": "pantry", "base_price": 3.99},
    {"name": "Beans Black Canned", "category": "pantry", "base_price": 0.54},
    {"name": "Beans Pinto Canned", "category": "pantry", "base_price": 0.54},
    {"name": "Chickpeas Canned", "category": "pantry", "base_price": 0.68},
    {"name": "Tomato Sauce Canned", "category": "pantry", "base_price": 0.72},
    {"name": "Peanut Butter Creamy", "category": "pantry", "base_price": 1.84},
    {"name": "Peanut Butter Crunchy", "category": "pantry", "base_price": 1.84},
    {"name": "Almond Butter", "category": "pantry", "base_price": 4.99},
    {"name": "Olive Oil Extra Virgin", "category": "pantry", "base_price": 5.47},
    {"name": "Vegetable Oil", "category": "pantry", "base_price": 4.97},
    {"name": "Coconut Oil", "category": "pantry", "base_price": 6.99},
    {"name": "Honey Raw", "category": "pantry", "base_price": 5.97},
    {"name": "Jelly Grape", "category": "pantry", "base_price": 1.29},
    {"name": "Jelly Strawberry", "category": "pantry", "base_price": 1.29},
    {"name": "Coffee Ground", "category": "pantry", "base_price": 3.97},
    {"name": "Tea Black", "category": "pantry", "base_price": 1.97},
    {"name": "Sugar Granulated", "category": "pantry", "base_price": 2.27},
    {"name": "Flour All Purpose", "category": "pantry", "base_price": 2.47},
    {"name": "Baking Powder", "category": "pantry", "base_price": 1.97},
    {"name": "Vanilla Extract", "category": "pantry", "base_price": 7.97},
    {"name": "Salt Iodized", "category": "pantry", "base_price": 0.88},
    {"name": "Black Pepper Ground", "category": "pantry", "base_price": 3.97},
    {"name": "Garlic Powder", "category": "pantry", "base_price": 2.47},
    {"name": "Onion Powder", "category": "pantry", "base_price": 2.47},
    {"name": "Cinnamon", "category": "pantry", "base_price": 2.97},
    {"name": "Cumin", "category": "pantry", "base_price": 2.47},
    {"name": "Chili Powder", "category": "pantry", "base_price": 2.27},
    {"name": "Paprika", "category": "pantry", "base_price": 2.27},
    {"name": "Oregano", "category": "pantry", "base_price": 2.97},
    {"name": "Basil Fresh", "category": "pantry", "base_price": 3.47},
    {"name": "Thyme", "category": "pantry", "base_price": 3.47},
    {"name": "Italian Seasoning", "category": "pantry", "base_price": 1.97},
    {"name": "Orange Juice", "category": "beverages", "base_price": 2.97},
    {"name": "Apple Juice", "category": "beverages", "base_price": 2.47},
    {"name": "Water Bottled", "category": "beverages", "base_price": 2.47},
    {"name": "Soda Cola", "category": "beverages", "base_price": 4.97},
    {"name": "Soda Sprite", "category": "beverages", "base_price": 4.97},
    {"name": "Lemonade", "category": "beverages", "base_price": 2.99},
    {"name": "Sports Drink Gatorade", "category": "beverages", "base_price": 2.99},
    {"name": "Frozen Pizza", "category": "frozen", "base_price": 4.97},
    {"name": "Frozen Vegetables Mixed", "category": "frozen", "base_price": 1.47},
    {"name": "Frozen Berries", "category": "frozen", "base_price": 2.47},
    {"name": "Frozen Chicken Breasts", "category": "frozen", "base_price": 5.99},
    {"name": "Ice Cream Vanilla", "category": "frozen", "base_price": 3.97},
    {"name": "Ice Cream Chocolate", "category": "frozen", "base_price": 3.97},
    {"name": "Chips Tortilla", "category": "snacks", "base_price": 1.47},
    {"name": "Chips Potato", "category": "snacks", "base_price": 1.97},
    {"name": "Cookies Chocolate Chip", "category": "snacks", "base_price": 2.47},
    {"name": "Granola Bars", "category": "snacks", "base_price": 1.97},
    {"name": "Almonds Raw", "category": "snacks", "base_price": 4.47},
    {"name": "Mixed Nuts", "category": "snacks", "base_price": 5.99},
    {"name": "Popcorn Microwave", "category": "snacks", "base_price": 2.99},
    {"name": "Pretzels", "category": "snacks", "base_price": 1.99},
]

stores = {
    'walmart': ('Great Value', 'w', 0.00),
    'target': ('Good & Gather', 't', 0.30),
    'marianos': ("Mariano's", 'm', 0.50),
    'jewel': ('Jewel', 'j', 0.60),
    'butera': ('Butera', 'b', 0.55),
    'caputos': ("Caputo's", 'c', 0.40),
    'petes': ("Pete's", 'p', 0.45),
}

for store_name, (brand, prefix, offset) in stores.items():
    items = []
    for idx, prod in enumerate(products, 1):
        price = round(prod['base_price'] + offset, 2)
        item = {
            "sku": f"{prefix}-{str(idx).zfill(3)}",
            "name": prod['name'],
            "brand": brand,
            "category": prod['category'],
            "size": {"value": 1 if prod['category'] in ['meat', 'produce'] else 16, "unit": "lb" if prod['category'] in ['meat', 'produce'] else "oz"},
            "price": price,
            "inStock": True
        }
        items.append(item)
    
    path = f"lib/providers/mock/data/{store_name}.json"
    with open(path, 'w') as f:
        json.dump(items, f, indent=2)
    print(f"✓ Created {store_name}.json with {len(items)} products")

print(f"\n✓ Successfully expanded all store catalogs!")
